package frc.robot.subsystems;

import static edu.wpi.first.units.Units.Degrees;
import static edu.wpi.first.units.Units.Inches;
import static edu.wpi.first.units.Units.Second;
import static edu.wpi.first.units.Units.Volts;

import java.util.List;
import java.util.Optional;
import java.util.function.Supplier;

import org.photonvision.EstimatedRobotPose;
import org.photonvision.targeting.PhotonPipelineResult;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.hardware.CANcoder;
import com.ctre.phoenix6.hardware.TalonFX;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModule;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;
import com.pathplanner.lib.path.PathConstraints;

import choreo.Choreo.TrajectoryLogger;
import choreo.auto.AutoFactory;
import choreo.trajectory.SwerveSample;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.controller.PIDController;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Pose3d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Transform2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.interpolation.InterpolatingDoubleTreeMap;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.kinematics.SwerveDriveOdometry;
import edu.wpi.first.math.kinematics.SwerveModulePosition;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.math.util.Units;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.smartdashboard.Field2d;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.robot.Constants;
import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;
import frc.robot.subsystems.vision.TagTracking;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
    private final SwerveRequest.ApplyFieldSpeeds m_pathApplyFieldSpeeds = new SwerveRequest.ApplyFieldSpeeds();
    private final PIDController m_pathXController = new PIDController(1, 0, 0);
    private final PIDController m_pathYController = new PIDController(1, 0, 0);
    private final PIDController m_pathThetaController = new PIDController(0.7, 0, 0);

    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;

    public SwerveDriveOdometry m_simOdometry = null;
    private final SwerveRequest.ApplyRobotSpeeds m_pathApplyRobotSpeeds = new SwerveRequest.ApplyRobotSpeeds();

    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();

    private boolean hubTrackingEnabled = false;
    private boolean passingModeEnabled = false;
    private boolean hubTrackingSOTMEnabled = false;
    private Pose2d hubPose;
    private InterpolatingDoubleTreeMap timeOfFlight = new InterpolatingDoubleTreeMap();

     private static final Field2d field = new Field2d();
     private static final Field2d fieldSOTM = new Field2d();

    private final Transform2d shooterTransform = new Transform2d(Units.inchesToMeters(-4.4), Units.inchesToMeters(-2), Rotation2d.kZero);

     private final TagTracking FrontLeftCamera = new TagTracking("angledCamera", Constants.CameraPositions.frontLeftTranslation);
    //private final TagTracking FrontRightCamera = new TagTracking("FrontRightCamera", Constants.CameraPositions.frontRightTranslation);

    /* SysId routine for characterizing translation. This is used to find PID gains for the drive motors. */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> setControl(m_translationCharacterization.withVolts(output)),
            null,
            this
        )
    );

    /* SysId routine for characterizing steer. This is used to find PID gains for the steer motors. */
    private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(7), // Use dynamic voltage of 7 V
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdSteer_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            volts -> setControl(m_steerCharacterization.withVolts(volts)),
            null,
            this
        )
    );
    private void configureAutoBuilder() {
        
        try {
            var config = RobotConfig.fromGUISettings();
            AutoBuilder.configure(
                () -> getState().Pose,   // Supplier of current robot pose
                this::resetPose,         // Consumer for seeding pose against auto
                () -> getState().Speeds, // Supplier of current robot speeds
                // Consumer of ChassisSpeeds and feedforwards to drive the robot
                (speeds, feedforwards) -> setControl(
                    m_pathApplyRobotSpeeds.withSpeeds(speeds)
                        .withWheelForceFeedforwardsX(feedforwards.robotRelativeForcesXNewtons())
                        .withWheelForceFeedforwardsY(feedforwards.robotRelativeForcesYNewtons())
                ),
                new PPHolonomicDriveController(
                    // PID constants for translation
                    new PIDConstants(10, 0, 0),
                    // PID constants for rotation
                    new PIDConstants(7, 0, 0)
                ),
                config,
                // Assume the path needs to be flipped for Red vs Blue, this is normally the case
                () -> DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Red,
                this // Subsystem for requirements
            );
        } catch (Exception ex) {
            DriverStation.reportError("Failed to load PathPlanner config and configure AutoBuilder", ex.getStackTrace());
        }
    }
    
    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle HeadingController.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on importing the log to SysId.
     */
    private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
        new SysIdRoutine.Config(
            /* This is in radians per second², but SysId only supports "volts per second" */
            Volts.of(Math.PI / 6).per(Second),
            /* This is in radians per second, but SysId only supports "volts" */
            Volts.of(Math.PI),
            null, // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdRotation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> {
                /* output is actually radians per second, but SysId only supports "volts" */
                setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                /* also log the requested output for SysId */
                SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
            },
            null,
            this
        )
    );

    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants   Drivetrain-wide constants for the swerve drive
     * @param modules               Constants for each specific module
     */
   
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        
        super(drivetrainConstants, modules);
        try{
        if(DriverStation.getAlliance().orElse(Alliance.Red) == Alliance.Blue){
            hubPose = Constants.FieldSetpoints.blueHubPose;
        }else{
            hubPose = Constants.FieldSetpoints.redHubPose;
        }
    }catch(Exception resultingError){
        hubPose = Constants.FieldSetpoints.redHubPose;
        DriverStation.reportWarning("Vision pose failed: " + resultingError.getMessage(), false);
    }
    configureAutoBuilder();
    fillTimeOfFlightLUT();
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If
     *                                unspecified or set to 0 Hz, this is 250 Hz on
     *                                CAN FD, and 100 Hz on CAN 2.0.
     * @param modules                 Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, modules);
        configureAutoBuilder();
        fillTimeOfFlightLUT();
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        Matrix<N3, N1> odometryStandardDeviation,
        Matrix<N3, N1> visionStandardDeviation,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation, modules);
        
        configureAutoBuilder();
        fillTimeOfFlightLUT();
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * Returns a command that applies the specified control request to this swerve drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }
    
    /**
     * Runs the SysId Quasistatic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }
    public void fillTimeOfFlightLUT(){
        double[] inputs = Constants.TimeOfFlightLUT.inputs;
        double[] outputs = Constants.TimeOfFlightLUT.outputs;
        for(int i=0; i< inputs.length;i++){
            timeOfFlight.put(inputs[i], outputs[i]);
        }
    }
    public Pose2d getRobotPose(){
        
        return this.getState().Pose;
    }
public Pose2d SOTMtest(){
final double flightTime = timeOfFlight.get(distanceToPoseSOTM(hubPose)); // seconds

    // getState().Speeds is robot-relative — convert to field-relative
    // using the robot's current heading
    ChassisSpeeds fieldRelativeSpeeds = ChassisSpeeds.fromRobotRelativeSpeeds(
        this.getState().Speeds,
        this.getState().Pose.getRotation()
    );

    // Multiply velocity (m/s) by time (s) to get a position offset (m)
    Translation2d velocityOffset = new Translation2d(
        fieldRelativeSpeeds.vxMetersPerSecond * flightTime,
        fieldRelativeSpeeds.vyMetersPerSecond * flightTime
    );

    // Add the offset to the current pose's translation
    // Rotation stays the same — we're offsetting position, not heading
    return new Pose2d(
        this.getState().Pose.getTranslation().plus(velocityOffset),
        this.getState().Pose.getRotation()
    );
}
public Pose2d getRobotPoseSOTM() {
    final double flightTime = timeOfFlight.get(distanceToPose(hubPose)); // seconds

    // getState().Speeds is robot-relative — convert to field-relative
    // using the robot's current heading
    ChassisSpeeds fieldRelativeSpeeds = ChassisSpeeds.fromRobotRelativeSpeeds(
        this.getState().Speeds,
        this.getState().Pose.getRotation()
    );

    // Multiply velocity (m/s) by time (s) to get a position offset (m)
    Translation2d velocityOffset = new Translation2d(
        fieldRelativeSpeeds.vxMetersPerSecond * flightTime,
        fieldRelativeSpeeds.vyMetersPerSecond * flightTime
    );

    // Add the offset to the current pose's translation
    // Rotation stays the same — we're offsetting position, not heading
    return new Pose2d(
        this.getState().Pose.getTranslation().plus(velocityOffset),
        this.getState().Pose.getRotation()
    );
}

    public Field2d getField2d(){
        return field;
    }
     public Field2d getField2dSOTM(){
         return fieldSOTM;
     }
    public void neutralTurretMode(){
        hubTrackingEnabled= false;
        passingModeEnabled = false;
        hubTrackingSOTMEnabled = false;
    }
    public void SOTMTurretMode(){
        hubTrackingEnabled= false;
        passingModeEnabled = false;
        hubTrackingSOTMEnabled = true;
    }
    public void hubTurretMode(){
        hubTrackingEnabled = true;
        passingModeEnabled = false;
        hubTrackingSOTMEnabled = false;
    }
    public void passingTurretMode(){
        hubTrackingEnabled = false;
        passingModeEnabled = true;
        hubTrackingSOTMEnabled = false;
    }
    public void toggleHubTracking(){
        if(hubTrackingEnabled==true){
            hubTrackingEnabled=false;
        }else{
            hubTrackingEnabled=true;
        }
    }
    public void togglePassingMode(){
        if(passingModeEnabled==true){
            passingModeEnabled=false;
        }else{
            passingModeEnabled=true;
        }
    }
    public double angleToHub(){
        
        // double output = Units.radiansToDegrees(Math.atan(
        //     (hubPose.getY()-getRobotPose().getY())
        //     /
        //     (hubPose.getX()-getRobotPose().getX())));
        double dx = (hubPose.getX()-getRobotPose().plus(shooterTransform).getX());
        double dy = (hubPose.getY()-getRobotPose().plus(shooterTransform).getY());
        double output = Units.radiansToDegrees(Math.atan2(dy, dx));
       SmartDashboard.putNumber("angle to hub dx", dx);
       SmartDashboard.putNumber("angle to hub dy", dy);
       SmartDashboard.putNumber("angle to hub", output);
        return output;
    }
    public double angleToHubSOTM(){
        double dx = (hubPose.getX()-getRobotPoseSOTM().plus(shooterTransform).getX());
        double dy = (hubPose.getY()-getRobotPoseSOTM().plus(shooterTransform).getY());
        double output = Units.radiansToDegrees(Math.atan2(dy, dx));
       
        return output;
    }
    public void followPath(SwerveSample sample) {
        m_pathThetaController.enableContinuousInput(-Math.PI, Math.PI);

        var pose = getState().Pose;

        var targetSpeeds = sample.getChassisSpeeds();
        targetSpeeds.vxMetersPerSecond += m_pathXController.calculate(
            pose.getX(), sample.x
        );
        targetSpeeds.vyMetersPerSecond += m_pathYController.calculate(
            pose.getY(), sample.y
        );
        targetSpeeds.omegaRadiansPerSecond += m_pathThetaController.calculate(
            pose.getRotation().getRadians(), sample.heading
        );

        setControl(
            m_pathApplyFieldSpeeds.withSpeeds(targetSpeeds)
                .withWheelForceFeedforwardsX(sample.moduleForcesX())
                .withWheelForceFeedforwardsY(sample.moduleForcesY())
        );
    }
    public AutoFactory createAutoFactory() {
        return createAutoFactory((sample, isStart) -> {});
    }
      public AutoFactory createAutoFactory(TrajectoryLogger<SwerveSample> trajLogger) {
        return new AutoFactory(
            () -> getState().Pose,
            this::resetPose,
            this::followPath,
            true,
            this,
            trajLogger
        );
    }
    public double distanceToPose(Pose2d pose) {

        // difference in x and y
        // double XDir = pose.getX() - getRobotPose().getX();
        // double yDir = pose.getY() - getRobotPose().getY();

        //System.out.println("X robot: " + getRobotPose().getX() + ", X stalk: " + pose.getX());
        // This uses the distance formula to get the distance
        //double distance = Math.sqrt(Math.pow(XDir, 2) + Math.pow(yDir, 2)); 
        double distance = pose.getTranslation().getDistance(getRobotPose()
        .plus(shooterTransform).getTranslation());

        return distance;
    }
    public double distanceToPoseSOTM(Pose2d pose) {

        // difference in x and y
        double distance = pose.getTranslation().getDistance(getRobotPoseSOTM().plus(shooterTransform).getTranslation());

        return distance;
    }
    /**
     * Runs the SysId Dynamic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Dynamic test
     * @return Command to run
     */
    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }
   public Alliance getAlliance(){
    return DriverStation.getAlliance().orElse(Alliance.Red);
}
    
    @Override
    public void periodic() {
        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is disabled.
         * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
         */
        SmartDashboard.putNumber("dist to red hub", distanceToPose(hubPose));
        SmartDashboard.putNumber("angletoHubSOTM", angleToHubSOTM());
        SmartDashboard.putNumber("angletohub", angleToHub());
        SmartDashboard.putNumber("drivetrain rotation", getRobotPose().getRotation().getDegrees());
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                    allianceColor == Alliance.Red
                        ? kRedAlliancePerspectiveRotation
                        : kBlueAlliancePerspectiveRotation
                );
                m_hasAppliedOperatorPerspective = true;
            });
        }
        
        field.setRobotPose(getRobotPose());
        fieldSOTM.setRobotPose(getRobotPose().plus(shooterTransform));
        SmartDashboard.putData("Field",getField2d());
        SmartDashboard.putData("FieldSOTM",getField2dSOTM());
        double rotation= getRobotPose().getRotation().getDegrees()+134;
        if(rotation<-270){
            rotation+=360;
        }else if(rotation>90){
            rotation -=360;
        }
        SmartDashboard.putNumber("rotation container", rotation);
         Turret.setRobotAngle(getRobotPose().getRotation().getDegrees()-180);
        if(hubTrackingEnabled){
            Turret.turretSetSetpoint(angleToHub()-rotation);
        }else if(passingModeEnabled){
            if(DriverStation.getAlliance().orElse(Alliance.Red) == Alliance.Blue){
                Turret.turretSetSetpoint(0-rotation);
            }else if(DriverStation.getAlliance().orElse(Alliance.Red) == Alliance.Red)
            Turret.turretSetSetpoint(180-rotation);
        

        }else if(hubTrackingSOTMEnabled){
            Turret.turretSetSetpoint(angleToHubSOTM()-rotation);
        }
       
        // if(FrontLeftCamera.tagOnScreen()&&!FrontRightCamera.tagOnScreen()){
        //    addVisionPose(FrontLeftCamera);
        // }else if(FrontRightCamera.tagOnScreen()&&!FrontLeftCamera.tagOnScreen()){
        //    addVisionPose(FrontRightCamera);
        // }else{

        //     addVisionPose(FrontRightCamera);
            addVisionPose(FrontLeftCamera);
       //} 
       // Object stuff
            // if(FrontRightCamera.hasTargets()){
            //     Pose2d objectpose =FrontRightCamera.getObjectPose(getRobotPose());
            //     SmartDashboard.putNumber("ObjectX", objectpose.getX());
            //      SmartDashboard.putNumber("ObjectY", objectpose.getY());
            // }

    }
   

     

      public void addVisionPose(TagTracking camera) {
        
        try {
            Optional<EstimatedRobotPose> cameraPoseEstimator = camera.getVisionBasedPose();
            List<PhotonPipelineResult> targets = camera.getAllUnreadResults();

            if(!targets.isEmpty()){
                PhotonPipelineResult target = targets.get(targets.size()-1);

                if(target.hasTargets() && target.getBestTarget() != null) {
                    if(cameraPoseEstimator != null && cameraPoseEstimator.isPresent() && target.getBestTarget().getPoseAmbiguity() < 0.2) {
                        Pose3d cameraPose = cameraPoseEstimator.get().estimatedPose;

                        // if the apriltag is too far, throw its results away
                        //if(camera.getApriltagDistance(getRobotPose(), target.getBestTarget().getFiducialId()) > 3) {// TO/DO test distance tracking
                            addVisionMeasurement(cameraPose.toPose2d(), cameraPoseEstimator.get().timestampSeconds);

                        //}
                    }
                }
            }
            
           
        } catch(Exception resultingError) {
            DriverStation.reportWarning("Vision pose failed: " + resultingError.getMessage(), false);
        }
        
    }

    private void startSimThread() {
         m_lastSimTime = Utils.getCurrentTimeSeconds();

        if (m_simOdometry == null) {
            SwerveModule<TalonFX, TalonFX, CANcoder>[] modules = getModules();
            SwerveModulePosition[] positions = new SwerveModulePosition[modules.length];
            for(int i = 0; i < modules.length; ++i) {
                positions[i] = modules[i].getCachedPosition();
            }
            m_simOdometry = new SwerveDriveOdometry(getKinematics(), Rotation2d.kZero, positions);
        }

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
            
            SwerveModule<TalonFX, TalonFX, CANcoder>[] modules = getModules();
            SwerveModulePosition[] positions = new SwerveModulePosition[modules.length];
            for(int i = 0; i < modules.length; ++i) {
                positions[i] = modules[i].getCachedPosition();
            }
            m_simOdometry.update(Rotation2d.fromDegrees(getPigeon2().getYaw().getValue().in(Degrees)), positions);
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }
     public void resetPose(Pose2d pose) {
        super.resetPose(pose);

        if(m_simOdometry != null) {
            m_simOdometry.resetPose(pose);
        }
    }
    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement
     *     in the form [x, y, theta]ᵀ, with units in meters and radians.
     */
    @Override
    public void addVisionMeasurement(
        Pose2d visionRobotPoseMeters,
        double timestampSeconds,
        Matrix<N3, N1> visionMeasurementStdDevs
    ) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }
    public Command driveToPose(Pose2d TargetPose, double maxPathSpeed, double maxPathAccel, double maxAngularSpeed, double maxAngularAccel) {
        PathConstraints constraints = new PathConstraints(
                maxPathSpeed, maxPathAccel, 
                Units.degreesToRadians(maxAngularSpeed), 
                Units.degreesToRadians(maxAngularAccel));

        return AutoBuilder.pathfindToPose(TargetPose, constraints, 0);
    }
}
